<a href="https://colab.research.google.com/github/Z0s-and-O1s/TNSIF_Training/blob/main/TNS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

---

##  Theory

NumPy (Numerical Python) is a powerful open-source Python library used for numerical computing.  
It provides support for:
- Multidimensional arrays (ndarray)
- Mathematical operations on arrays
- Linear algebra, Fourier transforms, random number generation

NumPy is faster than regular Python lists because it uses optimized **C libraries** internally.  
It is the foundation for many data science and machine learning libraries such as **Pandas, TensorFlow, SciPy, and Scikit-learn**.

---


##  Applications

- Handling large multidimensional arrays and matrices.
- Performing mathematical and statistical operations efficiently.
- Data preprocessing in Machine Learning.
- Basis for scientific computing libraries.
- Used in image processing, signal processing, and simulations.
- Vectorization (eliminating loops, improving performance).

## 3. List of Functions and Their Usage

Some important NumPy functions:

| Function | Usage |
|----------|--------|
| `np.array()` | Create an array |
| `np.arange(start, stop, step)` | Create array with range of values |
| `np.zeros((m,n))` | Create array filled with zeros |
| `np.ones((m,n))` | Create array filled with ones |
| `np.eye(n)` | Identity matrix |
| `np.linspace(start, stop, num)` | Create evenly spaced numbers |
| `np.random.rand(m,n)` | Random numbers between 0 and 1 |
| `np.shape` | Get dimensions of array |
| `np.reshape()` | Reshape array |
| `np.sum(), np.mean(), np.std()` | Aggregation functions |
| `np.min(), np.max(), np.argmin(), np.argmax()` | Min/Max values & indices |
| `np.dot(), np.matmul()` | Matrix multiplication |
| `np.transpose()` | Transpose of matrix |
| `np.sort()` | Sorting array |

---

In [ ]:
import numpy as np
arr1 = ([1,2,3,4])
print(arr1)
arr2 = ([1,2,3,4],[5,6,7,8])
print(arr2)

ar = np.array([1,2,3])
print(ar)

print(arr)


zero = np.zeros((2,3))
print('zero array : ',zero)

one = np.ones((3,3))
print('ones array : ',one)

identity = np.eye(4,4)
print(identity)

ls = np.linspace(1,3,5)
print(ls)

randnum = ((np.random.rand(2,3))*10).astype(int)
print(randnum)

#dimentions of arr2
ashp = np.shape(arr2)
print(ashp)

arr = np.arange(2,10).reshape(4,2)
print(arr)




[1, 2, 3, 4]
([1, 2, 3, 4], [5, 6, 7, 8])
[1 2 3]
[ 2  4  6  8 10 12 14 16 18]
zero array :  [[0. 0. 0.]
 [0. 0. 0.]]
ones array :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1.  1.5 2.  2.5 3. ]
[[4 4 6]
 [9 7 4]]
(2, 4)
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1 = ([1,2,3,4],[5,6,7,8])
array2 = ([4,6,8,3],[2,5,7,9])
addition = np.sum(array2)
print(addition)

Mean = np.mean(array1)
print(Mean)

standard = np.std(array1)
print(standard)

Min = np.min(array1)
print(Min)
Max = np.max(array1)
print(Max)

ArgMin = np.argmin(array1)
print(ArgMin)

ArgMax = np.argmax(array1)
print(ArgMax)

X = np.array(([3,4],[5,6]))
Y = np.array(([8,9],[6,7]))
Dot = np.dot(X,Y)
print(Dot)

mat = np.arange(2,10).reshape(2,4)
print(mat)
print(mat.T)

sorts = np.sort(array2)
print(sorts)

44
4.5
2.29128784747792
1
8
0
7
[[48 55]
 [76 87]]
[[2 3 4 5]
 [6 7 8 9]]
[[2 6]
 [3 7]
 [4 8]
 [5 9]]
[[3 4 6 8]
 [2 5 7 9]]


## Import and Usage

In [ ]:

# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9,10,11],[11,12,13]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((3,4))
ones = np.ones((2,3))
identity = np.eye(5)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(1, 45, 2)
linspace_arr = np.linspace(1, 2, 4)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)
otp =( (rand_arr*1000000)).astype(int)
print("Random Array:\n", otp)


1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]
Linspace: [1.         1.33333333 1.66666667 2.        ]
Random Array:
 [[0.95349615 0.66513588 0.33722098]
 [0.56871402 0.44083643 0.13513637]]
Random Array:
 [[953496 665135 337220]
 [568714 440836 135136]]


## Example

In [ ]:
# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(4,3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr - 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

# Example 5: Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))


Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [ 5 15 25 35]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]



Write a Python program using NumPy to perform the following:


Marks = 65, 78, 90, 55, 88

**Tasks:**

Create a NumPy array using these marks

Find the average marks

Find the highest marks

Find the lowest marks