<a href="https://colab.research.google.com/github/Z0s-and-O1s/TNSIF_Training/blob/main/TNS_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Functions on LIST
stud = [" shiva ", " sai ", " kiran ", " madhu", "shiva"]
stud.append("kiran")
stud.insert(3," saritha")
stud.remove("kiran")
stud.pop(2)
stud.sort()
stud.reverse()

print(stud.count("sai"))
print(type(stud))
print(stud)
print(len(stud))

0
<class 'list'>
['shiva', ' shiva ', ' saritha', ' sai ', ' madhu']
5


In [ ]:
# Functions on set
fruits = {"apple", "banana", "mango", "grape"}
fruits.
print(fruits)
print(type(fruits))

{'apple', 'mango', 'banana', 'grape'}
<class 'set'>


In [ ]:
name = input("Enter your name : ")
age = int(input("Enter your age: "))
nSub = int(input("Enter No. of Subjects you have: "))



StuName = []
StuSubj = set()
StuAge = ()
Sage = []
StuMarks = {}

StuName.append(name)
Sage.append(age)
StuAge = tuple(Sage)

for i in range (nSub):
  SubName = input("Enter Subject Name: ")
  StuSubj.add(SubName)

for namm in StuSubj:
  SubMarks = int(input(f"Enter {namm} subject marks: "))

  StuMarks[namm] = SubMarks


print("----------------STUDENT REPORT CARD----------------------")
print(f"Name of the Student: {name}")
print(f"Age : {age}")
for namm,marks in StuMarks.items():
  print(f"{namm} | {marks}")
total = sum(StuMarks.values())
avg = total / len(StuMarks)

print("Total Marks :", total)
print("Average Marks :", avg)

Enter your name : sai
Enter your age: 20
Enter No. of Subjects you have: 3
Enter Subject Name: Maths
Enter Subject Name: Science
Enter Subject Name: English
Enter Maths subject marks: 70
Enter Science subject marks: 80
Enter English subject marks: 90
----------------STUDENT REPORT CARD----------------------
Name of the Student: sai
Age : 20
Maths | 70
Science | 80
English | 90
Total Marks : 240
Average Marks : 80.0


In [5]:
# Create a numpy array containing nums from 1 -20 using in built functn
import numpy as np

nums = np.arange(1, 21)

print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
# Create an array of all zeros with 10 elements and convert it to matrix
z = np.zeros(10).reshape(5,2)

print(z)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
# create an array containing even nums from 2 to 20
even = np.arange(2, 20, 2)

print(even)

[ 2  4  6  8 10 12 14 16 18]


In [17]:
# create an array and find no of dimentions, shape, size, datatype and multiply every element by 2
no = (np.random.rand(1,10)*10).astype(int)

print(no)
print(no.ndim)
print(no.shape)
print(no.size)
print(no.dtype)
print(no * 2)

[[7 1 3 0 9 6 1 2 7 4]]
2
(1, 10)
10
int64
[[14  2  6  0 18 12  2  4 14  8]]


In [16]:
# create 1d array and find sum, mean, max, min
ToOp = (np.random.rand(1,6)*10).astype(int)

print(ToOp)
print(np.sum(ToOp))
print(np.mean(ToOp))
print(np.min(ToOp))
print(np.max(ToOp))


[[5 4 2 3 3 6]]
23
3.8333333333333335
2
6


In [6]:
import pandas as pd

st = pd.Series([1,2,3,4,5,6,7,8,9,10])

print("Original Series:\n", st)

print("\nDescription of Series:\n", st.describe())

print("\nStandard Deviation:\n", st.std())

print("\nMean:\n", st.mean())

print("\nMedian:\n", st.median())

print("\nMode:\n", st.mode())

print("\nMaximum Value:\n", st.max())

print("\nMinimum Value:\n", st.min())

print("\nElement at index -7 (iloc):\n", st.iloc[-7])

print("\nElement at label 5 (loc):\n", st.loc[5])

print("\nFiltered Series (elements <= 4) using boolean indexing:\n", st[st <= 4])

print("\nSeries after dropping label 6:\n", st.drop(6))

Original Series:
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

Description of Series:
 count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

Standard Deviation:
 3.0276503540974917

Mean:
 5.5

Median:
 5.5

Mode:
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

Maximum Value:
 10

Minimum Value:
 1

Element at index -7 (iloc):
 4

Element at label 5 (loc):
 6

Filtered Series (elements <= 4) using boolean indexing:
 0    1
1    2
2    3
3    4
dtype: int64

Series after dropping label 6:
 0     1
1     2
2     3
3     4
4     5
5     6
7     8
8     9
9    10
dtype: int64


In [7]:
import numpy as np

s = pd.Series([10, 20, np.nan, 40, 50, np.nan, 70])
print(s)

# is null, notnull,

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
5     NaN
6    70.0
dtype: float64
